version: "3.8"

services:
  backend:
    image: casvg/ticketsys-backend:latest
    restart: always
    environment:
      MONGO_URI: ${MONGO_URI}

    ports:
      - "3008:3008"

  frontend:
    image: casvg/ticketsys-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3007:5000"