name: TicketingSys CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "This is a test ${{ secrets.DOCKER_USERNAME }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        
      - name: test CI
        run: echo $MY_VARIABLE

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticketsys-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/ticketsys-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticketsys-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ticketsys-frontend:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Rootless Environment
        run: |
          echo "Setting up Docker rootless env..."
          echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          echo "export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock" >> $GITHUB_ENV

      - name: Pull Latest Backend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/ticketsys-backend:latest

      - name: Pull Latest Frontend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/ticketsys-frontend:latest

      - name: Stop and Remove Old Containers
        run: |
          docker compose down || true
          docker system prune -f

      - name: Run New Containers
        run: |
          docker compose up -d
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}